# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Albie
email: andrew@albie.io
description: > # this means to ignore newlines until "baseurl:"
  The Albie blog provides insight into Agile Development Methodologies and Practices to help foster high performing organizations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.albie.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

permalink: '/:title'
